name: Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  staticTesting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew build sonarqube --info
     
  dynamicTesting:
    runs-on: ubuntu-latest
    needs: staticTesting
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Execute Unit Tests
      run: ./gradlew test --tests '*UnitTests'
    - name: Execute Integration Tests
      run: ./gradlew test --tests '*IntegrationTests'

